[Appearance]
color_scheme_path=~/.config/qt6ct/colors/noctalia.conf
custom_palette=true
icon_theme=Papirus
standard_dialogs=default
style=Fusion

[Fonts]
fixed=@Variant(\0\0\0@\0\0\0\x12\0J\0\x65\0t\0\x42\0r\0\x61\0i\0n\0s\0\x4d\0o\0n\0o\0\x43\0r\0\x61\0\x66\0t\0\x12\0\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0\x32\x10)
general=@Variant(\0\0\0@\0\0\0\x16\0J\0\x65\0t\0\x42\0r\0\x61\0i\0n\0s\0\x4d\0o\0n\0o\0\x43\0 \0M\0\x65\0\x64\0i\0u\0m\0\x12\0\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0\x32\x10)

[PaletteEditor]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\xe2\0\0\0\x96\0\0\x3\xe2\0\0\x2\xdd\0\0\x3\xfe\0\0\x1p\0\0\0\0\0\0\0\0\v\0\0\0\0\x2\xe2\0\0\0\x96\0\0\x3\xe2\0\0\x2\xdd)

[Settings]
color_scheme=noctalia
