# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x092034ff
rootcolor = 0x092034ff
bordercolor = 0x5f6b74ff
focuscolor = 0x67abe5ff
maximizescreencolor = 0x5157e1ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0x9351e1ff
globalcolor = 0x0b528fff
overlaycolor = 0x090e76ff
