# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x142029ff
rootcolor = 0x142029ff
bordercolor = 0x5f6b74ff
focuscolor = 0x67ace4ff
maximizescreencolor = 0x5c61d6ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0x9466ccff
globalcolor = 0x0c538dff
overlaycolor = 0x10146fff
